/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ContactMessageDTO,
  SubmitMessageParams
} from '../../model';


/**
 * Submits a new contact message for a specific website domain.
 * @summary Submit a contact message
 */
export type submitMessageResponse200 = {
  data: ContactMessageDTO
  status: 200
}
    
export type submitMessageResponseSuccess = (submitMessageResponse200) & {
  headers: Headers;
};
;

export type submitMessageResponse = (submitMessageResponseSuccess)

export const getSubmitMessageUrl = (params: SubmitMessageParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/contact?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/contact`
}

export const submitMessage = async (contactMessageDTO: ContactMessageDTO,
    params: SubmitMessageParams, options?: RequestInit): Promise<submitMessageResponse> => {
  
  const res = await fetch(getSubmitMessageUrl(params),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactMessageDTO,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: submitMessageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as submitMessageResponse
}


