/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetAllProblemsParams,
  GetProblemBySlugParams,
  ProblemDetailDTO,
  ProblemListDTO
} from '../../model';


export type getAllProblemsResponse200 = {
  data: ProblemListDTO[]
  status: 200
}
    
export type getAllProblemsResponseSuccess = (getAllProblemsResponse200) & {
  headers: Headers;
};
;

export type getAllProblemsResponse = (getAllProblemsResponseSuccess)

export const getGetAllProblemsUrl = (params?: GetAllProblemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["tagIds","sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/problems?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/problems`
}

export const getAllProblems = async (params?: GetAllProblemsParams, options?: RequestInit): Promise<getAllProblemsResponse> => {
  
  const res = await fetch(getGetAllProblemsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllProblemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllProblemsResponse
}


export type getProblemBySlugResponse200 = {
  data: ProblemDetailDTO
  status: 200
}
    
export type getProblemBySlugResponseSuccess = (getProblemBySlugResponse200) & {
  headers: Headers;
};
;

export type getProblemBySlugResponse = (getProblemBySlugResponseSuccess)

export const getGetProblemBySlugUrl = (slug: string,
    params?: GetProblemBySlugParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/problems/${slug}?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/problems/${slug}`
}

export const getProblemBySlug = async (slug: string,
    params?: GetProblemBySlugParams, options?: RequestInit): Promise<getProblemBySlugResponse> => {
  
  const res = await fetch(getGetProblemBySlugUrl(slug,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getProblemBySlugResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProblemBySlugResponse
}


