/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetSitemapCategoriesParams,
  GetSitemapPostsParams,
  SitemapCategoryDTO,
  SitemapPostDTO
} from '../../model';


/**
 * Returns all published post slugs with their category slugs and last modified dates for a given domain and language.
 * @summary Get all post slugs for sitemap
 */
export type getSitemapPostsResponse200 = {
  data: SitemapPostDTO[]
  status: 200
}
    
export type getSitemapPostsResponseSuccess = (getSitemapPostsResponse200) & {
  headers: Headers;
};
;

export type getSitemapPostsResponse = (getSitemapPostsResponseSuccess)

export const getGetSitemapPostsUrl = (params: GetSitemapPostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/sitemap/posts?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/sitemap/posts`
}

export const getSitemapPosts = async (params: GetSitemapPostsParams, options?: RequestInit): Promise<getSitemapPostsResponse> => {
  
  const res = await fetch(getGetSitemapPostsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSitemapPostsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSitemapPostsResponse
}


/**
 * Returns all category slugs with last modified dates for a given domain and language.
 * @summary Get all category slugs for sitemap
 */
export type getSitemapCategoriesResponse200 = {
  data: SitemapCategoryDTO[]
  status: 200
}
    
export type getSitemapCategoriesResponseSuccess = (getSitemapCategoriesResponse200) & {
  headers: Headers;
};
;

export type getSitemapCategoriesResponse = (getSitemapCategoriesResponseSuccess)

export const getGetSitemapCategoriesUrl = (params: GetSitemapCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/sitemap/categories?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/sitemap/categories`
}

export const getSitemapCategories = async (params: GetSitemapCategoriesParams, options?: RequestInit): Promise<getSitemapCategoriesResponse> => {
  
  const res = await fetch(getGetSitemapCategoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSitemapCategoriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSitemapCategoriesResponse
}


