/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetAllSubmissionsParams,
  SubmissionDTO,
  SubmissionRequestVM
} from '../../model';


export type getAllSubmissionsResponse200 = {
  data: SubmissionDTO[]
  status: 200
}
    
export type getAllSubmissionsResponseSuccess = (getAllSubmissionsResponse200) & {
  headers: Headers;
};
;

export type getAllSubmissionsResponse = (getAllSubmissionsResponseSuccess)

export const getGetAllSubmissionsUrl = (params?: GetAllSubmissionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/submissions?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/submissions`
}

export const getAllSubmissions = async (params?: GetAllSubmissionsParams, options?: RequestInit): Promise<getAllSubmissionsResponse> => {
  
  const res = await fetch(getGetAllSubmissionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllSubmissionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllSubmissionsResponse
}


export type createSubmissionResponse200 = {
  data: SubmissionDTO
  status: 200
}
    
export type createSubmissionResponseSuccess = (createSubmissionResponse200) & {
  headers: Headers;
};
;

export type createSubmissionResponse = (createSubmissionResponseSuccess)

export const getCreateSubmissionUrl = () => {


  

  return `https://admin.is-hukuku.com/api/public/submissions`
}

export const createSubmission = async (submissionRequestVM: SubmissionRequestVM, options?: RequestInit): Promise<createSubmissionResponse> => {
  
  const res = await fetch(getCreateSubmissionUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      submissionRequestVM,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createSubmissionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSubmissionResponse
}


