/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetAllPostsParams,
  GetPostBySlugParams,
  PostTranslationDTO
} from '../../model';


/**
 * Retrieves all published post translations for a given website domain and language.
 * @summary List all posts by domain
 */
export type getAllPostsResponse200 = {
  data: PostTranslationDTO[]
  status: 200
}
    
export type getAllPostsResponseSuccess = (getAllPostsResponse200) & {
  headers: Headers;
};
;

export type getAllPostsResponse = (getAllPostsResponseSuccess)

export const getGetAllPostsUrl = (params: GetAllPostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/posts?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/posts`
}

export const getAllPosts = async (params: GetAllPostsParams, options?: RequestInit): Promise<getAllPostsResponse> => {
  
  const res = await fetch(getGetAllPostsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllPostsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllPostsResponse
}


/**
 * Fetches the details of a specific post using its category slug, post slug, website domain and language.
 * @summary Get a single post by slug
 */
export type getPostBySlugResponse200 = {
  data: PostTranslationDTO
  status: 200
}
    
export type getPostBySlugResponseSuccess = (getPostBySlugResponse200) & {
  headers: Headers;
};
;

export type getPostBySlugResponse = (getPostBySlugResponseSuccess)

export const getGetPostBySlugUrl = (categorySlug: string,
    slug: string,
    params: GetPostBySlugParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/posts/${categorySlug}/${slug}?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/posts/${categorySlug}/${slug}`
}

export const getPostBySlug = async (categorySlug: string,
    slug: string,
    params: GetPostBySlugParams, options?: RequestInit): Promise<getPostBySlugResponse> => {
  
  const res = await fetch(getGetPostBySlugUrl(categorySlug,slug,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getPostBySlugResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPostBySlugResponse
}


