/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ToggleSolvedResponseDTO
} from '../../model';


export type toggleSolvedResponse200 = {
  data: ToggleSolvedResponseDTO
  status: 200
}
    
export type toggleSolvedResponseSuccess = (toggleSolvedResponse200) & {
  headers: Headers;
};
;

export type toggleSolvedResponse = (toggleSolvedResponseSuccess)

export const getToggleSolvedUrl = (problemId: number,) => {


  

  return `https://admin.is-hukuku.com/api/public/user-problems/toggle/${problemId}`
}

export const toggleSolved = async (problemId: number, options?: RequestInit): Promise<toggleSolvedResponse> => {
  
  const res = await fetch(getToggleSolvedUrl(problemId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: toggleSolvedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as toggleSolvedResponse
}


export type getSolvedProblemIdsResponse200 = {
  data: number[]
  status: 200
}
    
export type getSolvedProblemIdsResponseSuccess = (getSolvedProblemIdsResponse200) & {
  headers: Headers;
};
;

export type getSolvedProblemIdsResponse = (getSolvedProblemIdsResponseSuccess)

export const getGetSolvedProblemIdsUrl = () => {


  

  return `https://admin.is-hukuku.com/api/public/user-problems/solved-ids`
}

export const getSolvedProblemIds = async ( options?: RequestInit): Promise<getSolvedProblemIdsResponse> => {
  
  const res = await fetch(getGetSolvedProblemIdsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSolvedProblemIdsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSolvedProblemIdsResponse
}


