/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AdminUserDTO {
  id?: number;
  /**
   * @minLength 1
   * @maxLength 50
   * @pattern ^(?>[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*)|(?>[_.@A-Za-z0-9-]+)$
   */
  login: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  firstName?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  lastName?: string;
  /**
   * @minLength 5
   * @maxLength 254
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 256
   */
  imageUrl?: string;
  activated?: boolean;
  /**
   * @minLength 2
   * @maxLength 10
   */
  langKey?: string;
  createdBy?: string;
  createdDate?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  authorities?: string[];
}
