/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminUserDTO } from './adminUserDTO';

export interface AuthResponseVM {
  user?: AdminUserDTO;
  id_token?: string;
  refresh_token?: string;
}
