/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WebsiteDTO } from './websiteDTO';
import type { FaqItemDTO } from './faqItemDTO';

export interface CategoryDTO {
  id?: number;
  imagePath?: string;
  createdDate?: string;
  updatedDate?: string;
  website: WebsiteDTO;
  faqs?: FaqItemDTO[];
}
