/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WebsiteDTO } from './websiteDTO';

export interface ContactMessageDTO {
  id?: number;
  fullName: string;
  /** @pattern ^[^@\s]+@[^@\s]+\.[^@\s]+$ */
  email: string;
  phone?: string;
  subject?: string;
  /** @minLength 1 */
  message: string;
  isRead?: boolean;
  ipAddress?: string;
  submittedDate?: string;
  website?: WebsiteDTO;
}
