/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CustomRegisterVM {
  /**
   * @minLength 1
   * @maxLength 50
   */
  login: string;
  /**
   * @minLength 5
   * @maxLength 254
   */
  email?: string;
  /**
   * @minLength 4
   * @maxLength 100
   */
  password: string;
}
