/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DifficultyStatsDTO } from './difficultyStatsDTO';

export interface DashboardStatsDTO {
  easy?: DifficultyStatsDTO;
  medium?: DifficultyStatsDTO;
  hard?: DifficultyStatsDTO;
}
