/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetAllProblemsDifficulty } from './getAllProblemsDifficulty';

export type GetAllProblemsParams = {
lang?: string;
title?: string;
difficulty?: GetAllProblemsDifficulty;
tagIds?: number[];
/**
 * Zero-based page index (0..N)
 * @minimum 0
 */
page?: number;
/**
 * The size of the page to be returned
 * @minimum 1
 */
size?: number;
/**
 * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
 */
sort?: string[];
};
