/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetAllProblemsDifficulty = typeof GetAllProblemsDifficulty[keyof typeof GetAllProblemsDifficulty];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAllProblemsDifficulty = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
} as const;
