/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetPostBySlugParams = {
/**
 * The target website domain (e.g. is-hukuku.com)
 */
domain: string;
/**
 * The language code for the translation
 */
lang?: string;
};
