/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PostDTO } from './postDTO';

export interface PostTranslationDTO {
  id?: number;
  /**
   * @minLength 0
   * @maxLength 2
   */
  languageCode: string;
  title: string;
  slug: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  summary?: string;
  content?: string;
  /**
   * @minLength 0
   * @maxLength 70
   */
  metaTitle?: string;
  /**
   * @minLength 0
   * @maxLength 160
   */
  metaDescription?: string;
  excerpt?: string;
  categorySlug?: string;
  modifiedDate?: string;
  post: PostDTO;
}
