/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WebsiteDTO } from './websiteDTO';
import type { TagDTO } from './tagDTO';
import type { CategoryDTO } from './categoryDTO';
import type { FaqItemDTO } from './faqItemDTO';

export interface PostDTO {
  id?: number;
  featuredImage?: string;
  publishedDate?: string;
  isPublished?: boolean;
  viewCount?: number;
  website: WebsiteDTO;
  tagses?: TagDTO[];
  category?: CategoryDTO;
  faqs?: FaqItemDTO[];
}
