/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProblemDetailDTODifficulty } from './problemDetailDTODifficulty';
import type { TagDTO } from './tagDTO';
import type { SolutionDTO } from './solutionDTO';

export interface ProblemDetailDTO {
  id?: number;
  difficulty?: ProblemDetailDTODifficulty;
  leetcodeUrl?: string;
  title?: string;
  slug?: string;
  description?: string;
  languageCode?: string;
  tags?: TagDTO[];
  solutions?: SolutionDTO[];
}
