/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProblemListDTODifficulty } from './problemListDTODifficulty';
import type { TagDTO } from './tagDTO';

export interface ProblemListDTO {
  id?: number;
  title?: string;
  slug?: string;
  difficulty?: ProblemListDTODifficulty;
  tags?: TagDTO[];
  isSolved?: boolean;
}
