/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PostInfo } from './postInfo';

export interface PublicCategoryPostsDTO {
  id?: number;
  slug?: string;
  name?: string;
  posts?: PostInfo[];
}
