/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SubmissionRequestVMStatus } from './submissionRequestVMStatus';

export interface SubmissionRequestVM {
  problemId: number;
  status: SubmissionRequestVMStatus;
  programmingLanguage: string;
  runtimeMs?: number;
}
