/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SubmissionRequestVMStatus = typeof SubmissionRequestVMStatus[keyof typeof SubmissionRequestVMStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubmissionRequestVMStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMEOUT',
  RUNTIME_ERROR: 'RUNTIME_ERROR',
  COMPILE_ERROR: 'COMPILE_ERROR',
} as const;
