/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SubmissionDTOStatus } from './submissionDTOStatus';

export interface SubmissionDTO {
  id?: number;
  problemTitle?: string;
  problemSlug?: string;
  status?: SubmissionDTOStatus;
  programmingLanguage?: string;
  runtimeMs?: number;
  submittedAt?: string;
}
