/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WebsiteDTO } from './websiteDTO';
import type { PostDTO } from './postDTO';

export interface TagDTO {
  id?: number;
  website: WebsiteDTO;
  postses?: PostDTO[];
}
