/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserSolvedProblemDTODifficulty } from './userSolvedProblemDTODifficulty';

export interface UserSolvedProblemDTO {
  title?: string;
  slug?: string;
  difficulty?: UserSolvedProblemDTODifficulty;
  solvedDate?: string;
}
