/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface WebsiteDTO {
  id?: number;
  name: string;
  domain: string;
  isActive?: boolean;
}
