/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  DashboardStatsDTO,
  GetSolvedProblemsParams,
  UserSolvedProblemDTO
} from '../../model';


export type getDashboardStatsResponse200 = {
  data: DashboardStatsDTO
  status: 200
}
    
export type getDashboardStatsResponseSuccess = (getDashboardStatsResponse200) & {
  headers: Headers;
};
;

export type getDashboardStatsResponse = (getDashboardStatsResponseSuccess)

export const getGetDashboardStatsUrl = () => {


  

  return `https://admin.is-hukuku.com/api/public/dashboard/stats`
}

export const getDashboardStats = async ( options?: RequestInit): Promise<getDashboardStatsResponse> => {
  
  const res = await fetch(getGetDashboardStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getDashboardStatsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDashboardStatsResponse
}


export type getSolvedProblemsResponse200 = {
  data: UserSolvedProblemDTO[]
  status: 200
}
    
export type getSolvedProblemsResponseSuccess = (getSolvedProblemsResponse200) & {
  headers: Headers;
};
;

export type getSolvedProblemsResponse = (getSolvedProblemsResponseSuccess)

export const getGetSolvedProblemsUrl = (params?: GetSolvedProblemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["sort"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : v.toString());
      });
      return;
    }
      
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://admin.is-hukuku.com/api/public/dashboard/solved-problems?${stringifiedParams}` : `https://admin.is-hukuku.com/api/public/dashboard/solved-problems`
}

export const getSolvedProblems = async (params?: GetSolvedProblemsParams, options?: RequestInit): Promise<getSolvedProblemsResponse> => {
  
  const res = await fetch(getGetSolvedProblemsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSolvedProblemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSolvedProblemsResponse
}


