/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  GetAllTagsParams,
  TagListDTO
} from '../../model';


export type getAllTagsResponse200 = {
  data: TagListDTO[]
  status: 200
}
    
export type getAllTagsResponseSuccess = (getAllTagsResponse200) & {
  headers: Headers;
};
;

export type getAllTagsResponse = (getAllTagsResponseSuccess)

export const getGetAllTagsUrl = (params: GetAllTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:9000/api/public/tags?${stringifiedParams}` : `http://localhost:9000/api/public/tags`
}

export const getAllTags = async (params: GetAllTagsParams, options?: RequestInit): Promise<getAllTagsResponse> => {
  
  const res = await fetch(getGetAllTagsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllTagsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllTagsResponse
}


