/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AuthResponseVM,
  CustomLoginVM,
  CustomRegisterVM,
  RefreshVM
} from '../../model';


export type registerAccountResponse201 = {
  data: void
  status: 201
}
    
export type registerAccountResponseSuccess = (registerAccountResponse201) & {
  headers: Headers;
};
;

export type registerAccountResponse = (registerAccountResponseSuccess)

export const getRegisterAccountUrl = () => {


  

  return `http://localhost:9000/api/public/auth/register`
}

export const registerAccount = async (customRegisterVM: CustomRegisterVM, options?: RequestInit): Promise<registerAccountResponse> => {
  
  const res = await fetch(getRegisterAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      customRegisterVM,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerAccountResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerAccountResponse
}


export type refreshResponse200 = {
  data: AuthResponseVM
  status: 200
}
    
export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
;

export type refreshResponse = (refreshResponseSuccess)

export const getRefreshUrl = () => {


  

  return `http://localhost:9000/api/public/auth/refresh`
}

export const refresh = async (refreshVM: RefreshVM, options?: RequestInit): Promise<refreshResponse> => {
  
  const res = await fetch(getRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshVM,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: refreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as refreshResponse
}


export type loginResponse200 = {
  data: AuthResponseVM
  status: 200
}
    
export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
;

export type loginResponse = (loginResponseSuccess)

export const getLoginUrl = () => {


  

  return `http://localhost:9000/api/public/auth/login`
}

export const login = async (customLoginVM: CustomLoginVM, options?: RequestInit): Promise<loginResponse> => {
  
  const res = await fetch(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      customLoginVM,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}


